//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace prjCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCustomer
    {
        public int fId { get; set; }

        [Display(Name = "姓名")]
        [Required(ErrorMessage ="姓名是必填喔!")]
        public string fName { get; set; }

        [Display(Name = "性別")]
        [Required(ErrorMessage ="性別是必填喔!")]
        public int Sex { get; set; }

        [Display(Name = "生日")]
        [Required(ErrorMessage ="生日是必填喔!")]
        public Nullable<System.DateTime> Birthday { get; set; }

        [Display(Name = "電話")]
        [Required(ErrorMessage = "電話是必填喔!")]
        [StringLength(10, MinimumLength = 8, ErrorMessage = "(0),至少要有(8)個字")]
        public string fPhone { get; set; }

        [Display(Name = "照片")]        
        public string fAddress { get; set; }

        public System.DateTime CreateDate { get; set; }
    }
}
